### ISSUE TITLE
Issues with running this on the Raspberry pi 4

### ISSUE THREAD

**Issue by kittentakara** [FreeTAKTeam/FreeTakServer#107]
I am getting this after following the installation guide for Raspberry Pi?

Any Suggestions? 

root@raspberrypi:/home/pi# sudo python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP 0.0.0.0 -AutoStart True
2021-01-07 13:27:18,049 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-01-07 13:27:18,049 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,051 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-01-07 13:27:18,051 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,052 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("User")
2021-01-07 13:27:18,053 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,055 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("DataPackages")
2021-01-07 13:27:18,055 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,056 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("VideoStreams")
2021-01-07 13:27:18,056 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,056 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Archive")
2021-01-07 13:27:18,056 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,057 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Chat")
2021-01-07 13:27:18,057 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,058 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Color")
2021-01-07 13:27:18,058 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,058 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Contact")
2021-01-07 13:27:18,058 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,059 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Dest")
2021-01-07 13:27:18,059 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,059 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Emergency")
2021-01-07 13:27:18,060 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,060 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Link")
2021-01-07 13:27:18,060 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,061 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Marti")
2021-01-07 13:27:18,061 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,062 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Precisionlocation")
2021-01-07 13:27:18,062 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,063 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Remarks")
2021-01-07 13:27:18,063 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,064 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Serverdestination")
2021-01-07 13:27:18,064 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,065 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Status")
2021-01-07 13:27:18,066 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,066 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Summary")
2021-01-07 13:27:18,067 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,068 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Takv")
2021-01-07 13:27:18,068 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,068 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Track")
2021-01-07 13:27:18,068 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,069 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Uid")
2021-01-07 13:27:18,069 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,070 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Usericon")
2021-01-07 13:27:18,071 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,071 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Detail")
2021-01-07 13:27:18,072 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,072 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Point")
2021-01-07 13:27:18,073 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,073 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Event")
2021-01-07 13:27:18,074 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,074 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ActiveEmergencys")
2021-01-07 13:27:18,074 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,075 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("APIUsers")
2021-01-07 13:27:18,075 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,076 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheckKeywords")
2021-01-07 13:27:18,076 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,076 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheckData")
2021-01-07 13:27:18,077 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:27:18,077 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheck")
2021-01-07 13:27:18,078 INFO sqlalchemy.engine.base.Engine ()
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 5, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 43, in <module>
    os.mkdir(MainConfig.ExCheckMainPath)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/FreeTAKServer/ExCheck'

**Comment by naman108** [comment]
what is your python version?

**Comment by kittentakara** [comment]
3.7, 

Its not very clear, realised now, that I have to changed the Python Version in the Config, and its working better now, but I am not getting this 

start 213
starting now
0.0.0.0
8080
(4267) wsgi starting up on http://0.0.0.0:8080
start 213
starting SSL now
0.0.0.0
8443
CoTService started
SSL CoTService started
2021-01-07 13:36:11,643 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-01-07 13:36:11,644 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,645 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-01-07 13:36:11,645 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,647 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("User")
2021-01-07 13:36:11,648 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,653 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("DataPackages")
2021-01-07 13:36:11,653 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,655 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("VideoStreams")
2021-01-07 13:36:11,655 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,657 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Archive")
2021-01-07 13:36:11,658 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,659 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Chat")
2021-01-07 13:36:11,659 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,661 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Color")
2021-01-07 13:36:11,662 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,664 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Contact")
2021-01-07 13:36:11,664 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,665 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Dest")
2021-01-07 13:36:11,665 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-01-07 13:36:11,666 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,666 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,667 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Emergency")
2021-01-07 13:36:11,667 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,667 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-01-07 13:36:11,668 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,668 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Link")
2021-01-07 13:36:11,668 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,669 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Marti")
2021-01-07 13:36:11,669 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("User")
2021-01-07 13:36:11,669 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,670 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,670 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Precisionlocation")
2021-01-07 13:36:11,671 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,672 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Remarks")
2021-01-07 13:36:11,672 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,673 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Serverdestination")
2021-01-07 13:36:11,673 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,674 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Status")
2021-01-07 13:36:11,674 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("DataPackages")
2021-01-07 13:36:11,674 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,674 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,675 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Summary")
2021-01-07 13:36:11,675 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("VideoStreams")
2021-01-07 13:36:11,675 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,675 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,676 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Takv")
2021-01-07 13:36:11,676 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Archive")
2021-01-07 13:36:11,677 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,677 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,677 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Track")
2021-01-07 13:36:11,677 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Chat")
2021-01-07 13:36:11,678 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,678 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,678 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Uid")
2021-01-07 13:36:11,679 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Color")
2021-01-07 13:36:11,679 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,679 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,680 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Usericon")
2021-01-07 13:36:11,680 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Contact")
2021-01-07 13:36:11,680 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,680 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,681 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Detail")
2021-01-07 13:36:11,681 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Dest")
2021-01-07 13:36:11,681 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,681 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,682 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Emergency")
2021-01-07 13:36:11,682 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Point")
2021-01-07 13:36:11,682 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,682 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,683 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Event")
2021-01-07 13:36:11,683 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Link")
2021-01-07 13:36:11,683 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,683 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,684 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Marti")
2021-01-07 13:36:11,684 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ActiveEmergencys")
2021-01-07 13:36:11,684 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,684 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,685 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("APIUsers")
2021-01-07 13:36:11,685 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Precisionlocation")
2021-01-07 13:36:11,685 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,685 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,686 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheckKeywords")
2021-01-07 13:36:11,686 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Remarks")
2021-01-07 13:36:11,687 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,687 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,687 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Serverdestination")
2021-01-07 13:36:11,687 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheckData")
2021-01-07 13:36:11,688 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,688 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,688 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheck")
2021-01-07 13:36:11,688 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Status")
2021-01-07 13:36:11,689 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,689 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,689 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Summary")
2021-01-07 13:36:11,690 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,691 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Takv")
2021-01-07 13:36:11,692 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,694 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Track")
2021-01-07 13:36:11,695 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,696 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Uid")
2021-01-07 13:36:11,696 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,698 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Usericon")
2021-01-07 13:36:11,698 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,699 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Detail")
2021-01-07 13:36:11,699 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,701 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Point")
2021-01-07 13:36:11,701 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,702 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Event")
2021-01-07 13:36:11,702 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,703 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ActiveEmergencys")
2021-01-07 13:36:11,704 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,705 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("APIUsers")
2021-01-07 13:36:11,705 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,706 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheckKeywords")
server started
2021-01-07 13:36:11,706 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,708 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheckData")
2021-01-07 13:36:11,708 INFO sqlalchemy.engine.base.Engine ()
2021-01-07 13:36:11,709 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("ExCheck")
2021-01-07 13:36:11,709 INFO sqlalchemy.engine.base.Engine ()
ssl cot service starting

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

'NoneType' object has no attribute 'xmlString'

**Comment by naman108** [comment]
looks like you havent generated valid certificates this is the best tool for the job with FTS for generating certs https://github.com/lennisthemenace/ATAK-Certs afterwards you can specify the path in the MainConfig.py

**Comment by kittentakara** [comment]
Still learning CLI again, been almost 15 years and I can't remember half it :P

So thank for you the help and taking time to answer my silly answers. I am trying to set up this to help mountain rescue in my area.

**Comment by naman108** [comment]
did the cert generation fix the issue?

**Comment by brothercorvo** [comment]
fixed
