### ISSUE TITLE
Issue connecting to server for data packages

### ISSUE THREAD

**Issue by nerdasaur** [FreeTAKTeam/FreeTakServer#108]
I've been playing around with FTS on an android device i have and WinTAK.  I appear to be able to upload and download datapackages on ATAK, but i'm getting error messages when attempting to do so on WinTAK.  

I've installed the generic certificates (at least i think i have), and there are 2 servers noted (TCP and SSL).  Forgive me here, i'm probably just a complete moron.  When attempting to download DataPackages from TCP server I get the following error:

Error retrieving packages from server

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MissionPackageTool.Services.PackagesTakClient.<GetPackagesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MissionPackageTool.DockPanes.MissionPackagesDockPane.<GetPackagesFromServer>d__104.MoveNext()

i attempt to download packages from SSL server and get this error message (I probably didn't do this correctly):

Error retrieving packages from server

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MissionPackageTool.Services.PackagesTakClient.<GetPackagesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MissionPackageTool.DockPanes.MissionPackagesDockPane.<GetPackagesFromServer>d__104.MoveNext()

Oddly enough, I get timeout errors when uploading data packages (WinTAK) yet the package can be accessed on server by my Android device.  Something hasn't been done correctly, and it's got to be something i did.

**Comment by nerdasaur** [comment]
My sincerest apologies, it was 100% operator error

**Comment by bamaham93** [comment]
I'm having the same issue and am trying to see what exactly the problem is. Is it some sort of port misconfiguration between WinTAK and the FreeTAK Server instance?

**Comment by brothercorvo** [comment]
Probably you are using a recent version of wintak that disables data packages on TCP. This is a client issue.  If this is not the case open a new issue
