### ISSUE TITLE
FTS 1.5 fails to open database file

### ISSUE THREAD

**Issue by capitanxitry** [FreeTAKTeam/FreeTakServer#123]
Hello!

Tried to install Win7 x64. Used both py 3.8 and 3.7 either x32 and x64. The same result. 

C:\Users\user>pip check FreeTAKServer
No broken requirements found.

C:\Users\user>python -m FreeTAKServer.controllers.services.FTS
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\b
ase.py", line 2336, in _wrap_pool_connect
    return fn()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\imp
l.py", line 241, in _do_get
    return self._create_connection()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\util\lan
ghelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\util\com
pat.py", line 182, in raise_
    raise exception
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\s
trategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\d
efault.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\runpy.py", line 193, in _run_modu
le_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\FreeTAKServer\contr
ollers\services\FTS.py", line 5, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPData
PackageService as TCPFlaskFunctions
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\FreeTAKServer\contr
ollers\services\TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app,
eventlet, const
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\FreeTAKServer\contr
ollers\services\DataPackageServer.py", line 25, in <module>
    dbController = DatabaseController()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\FreeTAKServer\contr
ollers\DatabaseControllers\DatabaseController.py", line 54, in __init__
    self.engine = self.create_engine()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\FreeTAKServer\contr
ollers\DatabaseControllers\DatabaseController.py", line 77, in create_engine
    if engine.dialect.has_table(engine, 'SystemUser') == False:
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\dialects
\sqlite\base.py", line 1640, in has_table
    connection, "table_info", table_name, schema=schema
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\dialects
\sqlite\base.py", line 2153, in _get_table_pragma
    cursor = connection.execute(statement)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\b
ase.py", line 2234, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\b
ase.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\b
ase.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\b
ase.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\util\com
pat.py", line 182, in raise_
    raise exception
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\b
ase.py", line 2336, in _wrap_pool_connect
    return fn()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\imp
l.py", line 241, in _do_get
    return self._create_connection()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\util\lan
ghelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\util\com
pat.py", line 182, in raise_
    raise exception
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\pool\bas
e.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\s
trategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\sqlalchemy\engine\d
efault.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open datab
ase file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

C:\Users\user>

Any ideas? I'm a bit lammer, too complicated for me... Thank you

**Comment by brothercorvo** [comment]
Window 7 is even not supported by microsoft. Try with a update version. We have a guide for win systems now

**Comment by rmorgan999** [comment]
I have the same issue when running on Windows 10 Pro, Version 20H2

**Comment by Cale-Torino** [comment]
@rmorgan999 Perhaps try to run the console with Admin privileges.

**Comment by rmorgan999** [comment]
I have tried that.  It's the same
