### ISSUE TITLE
FTS fail to launch

### ISSUE THREAD

**Issue by L-Belluomini** [FreeTAKTeam/FreeTakServer#135]
fresh PI OS lite install on PI 2 b+
followed doc ( https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/PyPi/Linux/Install/ )
FTS check show (
pip3 check FreeTakServer 
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2962, in _dep_map
    return self.__dep_map
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2756, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2953, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2756, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/check.py", line 19, in run
    package_set = create_package_set_from_installed()
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/check.py", line 41, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2700, in requires
    dm = self._dep_map
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2964, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2973, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2955, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1413, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte
)
tryng to launch FTS (
sudo python3 -m FreeTAKServer.controllers.services.FTS
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 5, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 13, in <module>
    from FreeTAKServer.controllers.DatabaseControllers.DatabaseController import DatabaseController
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/DatabaseControllers/DatabaseController.py", line 1, in <module>
    import FreeTAKServer.controllers.DatabaseControllers.table_controllers
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/DatabaseControllers/table_controllers.py", line 3, in <module>
    from FreeTAKServer.model.SQLAlchemy.User import User
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/model/SQLAlchemy/User.py", line 18, in <module>
    from FreeTAKServer.model.SQLAlchemy.system_user import SystemUser
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/model/SQLAlchemy/system_user.py", line 6, in <module>
    from flask_login import UserMixin
  File "/usr/local/lib/python3.7/dist-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.7/dist-packages/flask_login/login_manager.py", line 12, in <module>
    from flask import (_request_ctx_stack, abort, current_app, flash, redirect,
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
ValueError: source code string cannot contain null bytes
)
suggestion ?

**Comment by L-Belluomini** [comment]
[SOLVED]searching for the root cause I find it was a problem installing & updating pip.
re-flashed the sd and reinstalled pip solved the issue.
NOTE: I had an other problem and found the solution posted on Discord, looks like a dependency is missing as installing libxslt-dev solved, you may want to include this package to the installation guide
