### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by AEU2020** [FreeTAKTeam/FreeTakServer#196]
hi guys iam newby in all that stuff and complete new in the PI world but i want to try wintak and atak with freetakserver for my airsoft team 
but i have no clue how to fix this error can someone maybe help me ???
the last command has an error at the end

sudo python3 -m FreeTAKServer.controllers.services.FTS
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 6, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 50, in <module>
    os.mkdir(MainConfig.ExCheckMainPath)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/FreeTAKServer/ExCheck'
pi@AEU-SERVER:~ $

**Comment by naman108** [comment]
please refer to issue 192
