### ISSUE TITLE
Error while installing on Raspberry Pi / Python 3.7

### ISSUE THREAD

**Issue by H-Tudor** [FreeTAKTeam/FreeTakServer#204]
While attempting to install on a Raspberry Pi 4 server, using the default Python 3.7, the install wizard tried to access the path for Python 3.8, which is not installed.

```
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 6, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 50, in <module>
    os.mkdir(MainConfig.ExCheckMainPath)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/FreeTAKServer/ExCheck'
```

**Comment by H-Tudor** [comment]
Fix: 
```
sudo nano  /usr/local/lib/python3.7/dist-packages/FreeTAKServer/controllers/configuration/MainConfig.py
```
Replace
```
python_version = 'python3.8'
```
with
```
python_version = 'python3.7'
```
