### ISSUE TITLE
Exceptions Thrown At Runtime

### ISSUE THREAD

**Issue by NullVibes** [FreeTAKTeam/FreeTakServer#207]
After installation & modification for Python3.9 (#192), the error `AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'` is thrown 6 times before `starting server` occurs.  Then, FTS restarts every 30 seconds.

[FULL DUMP]
pi@ATAKpi:~ $ sudo python3 -m FreeTAKServer.controllers.services.FTS
CA found locally, not generating a new one
Certificate file exists, aborting.
Certificate file exists, aborting.
start 213
starting now
Exception ignored in: <function _after_fork at 0xb273bbf8>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
running api
Exception ignored in: <function _after_fork at 0xb273bbf8>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
0.0.0.0
8080
(6834) wsgi starting up on http://0.0.0.0:8080
start 213
starting SSL now
Exception ignored in: <function _after_fork at 0xb273bbf8>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
0.0.0.0
8443
(6835) wsgi starting up on https://0.0.0.0:8443
event event about to be created
CoTService started
Exception ignored in: <function _after_fork at 0xb273bbf8>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
SSL CoTService started
Exception ignored in: <function _after_fork at 0xb273bbf8>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
Exception ignored in: <function _after_fork at 0xb273bbf8>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
server started
ssl cot service starting
server started

 running ssl 

started federation federate service
time since last reset 0:00:30.001775

resetting

**Comment by brothercorvo** [comment]
It looks like you have the wrong dependencies for python 3.9

**Comment by brothercorvo** [comment]
Try again with 1.9.5 and Python 3.8, follow the instructions of the video
https://www.youtube.com/watch?v=ot3PNY903ns&ab_channel=FreeTAKTeam

**Comment by cslamar** [comment]
I've experienced the same issue with Python 3.9 and FTS 1.9.8.  After some digging it looks like the version of eventlet has this as a known issue.  In my test environment I updated eventlet to 0.30.0 and the issue went away.  I have not noticed any abnormal behavior in FTS after doing so, and the error no longer appears.

**Comment by brothercorvo** [comment]
this has been adreessed with the ZeroTouch installer , closing it
