### ISSUE TITLE
new install issue

### ISSUE THREAD

**Issue by frozenstitches** [FreeTAKTeam/FreeTakServer#212]
I am following the install guide on a ubuntu LCX
at this command to be able to configure the server:
`sudo python3 -m FreeTAKServer.controllers.services.FTS `

I receive this output:
`root@PROX-ATAK01:~# sudo python3 -m FreeTAKServer.controllers.services.FTS 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 6, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.6/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.6/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 50, in <module>
    os.mkdir(MainConfig.ExCheckMainPath)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/FreeTAKServer/ExCheck'
root@PROX-ATAK01:~# 
`

**Comment by brothercorvo** [comment]
you are trying to install FTS using Python 3.6. Upgrade to Python 3.8

**Comment by bhill07** [comment]
I had the same issue. I fixed it by copying the entire directory in the python3.6 location to the python3.8 directory.

**Comment by brothercorvo** [comment]
Check this out @jonaugustine
