### ISSUE TITLE
exCheck functionality is broken

### ISSUE THREAD

**Issue by brothercorvo** [FreeTAKTeam/FreeTakServer#213]
In general it appears to be an issue of paths:

# WinTAK 4.4:
- create a template: OK and uploaded to server
- Create a template from existing: fails
- Create a new list: OK
- Join existing list: List empty
- Edit a existing list: fails
- Complete item: OK on client but fails on the server
![image](https://user-images.githubusercontent.com/60719165/144262245-deee5b01-0160-4f91-a82f-0f3e0fcedef7.png)

# ATAK 4.3
- create a template: OK
- Create a template from existing: (failed to connect to the server)
- Create a new list: Fails (error in server connection ) [Pub + Helio]
- Join existing list: Fails (error in server connection ) [Pub + Helio]
- Edit a existing list: fails
- - Complete item: fails

**Comment by brothercorvo** [comment]
Output from FTS

```(53724) accepted ('100.42.255.101', 13153)
100.42.255.101 - - [01/Dec/2021 15:32:19] "POST /Marti/api/excheck/template?clientUid=ANDROID-351811095448994 HTTP/1.1" 200 208 0.058916
<FreeTAKServer.model.testobj.testobj object at 0x7f79043890d0>
<FreeTAKServer.model.testobj.testobj object at 0x7f7906411250>
(53724) accepted ('100.42.255.101', 59771)
Exception on /Marti/api/excheck/174a1cfa-9ee0-40ec-aefd-93b70f621402/start [POST                                        ]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi                                        _app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full                                        _dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 16                                        5, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in hand                                        le_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in re                                        raise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full                                        _dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in disp                                        atch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/service                                        s/DataPackageServer.py", line 410, in startList
    details.append(starttime)
TypeError: appenhandling reg data
handling reg data
```

**Comment by brothercorvo** [comment]
eerro in wintak by updating

```
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'replace'
135.129.117.179 - - [01/Dec/2021 15:40:14] "PUT /Marti/api/excheck/checklist/8e6cc4bb-a41d-4765-a06a-d46644833ade/task/8f8beefa-5592-48d7-8b1f-3d99389c2276?clientUid=S-1-5-21-2016644612-1395674371-728433739-1001 HTTP/1.1" 500 458 0.098516
```

**Comment by brothercorvo** [comment]
Upload a new template ATAK
```

(53724) accepted ('100.42.255.101', 49358)
Exception on /Marti/api/excheck/1eac3ff0-430f-4b97-9c04-5366db4f23a0/start [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 410, in startList
    details.append(starttime)
TypeError: append() argument must be xml.etree.ElementTree.Element, not lxml.etree._Element
100.42.255.101 - - [01/Dec/2021 15:42:55] "POST /Marti/api/excheck/1eac3ff0-430f-4b97-9c04-5366db4f23a0/start?clientUid=ANDROID-351811095448994&callsign=corvo&name=aa&description=ss&startTime=2021-12-01T15%3A42%3A54.661Z HTTP/1.1" 500 482 0.004122
```
