### ISSUE TITLE
Windows Version Installation Issues

### ISSUE THREAD

**Issue by rcgordy** [FreeTAKTeam/FreeTakServer#344]
I'm very new to Python, please keep in mind, but I followed the text tutorial (and found some videos) a few times and have been getting the same issues when attempting to start the server.

I am attempting to install the Windows version and am using Python 3.8.9.  Path to install is C:\Software\python.

Issue(s):

When attempting to start the server:

C:\Users\richg>python -m FreeTAKServer.controllers.services.FTS
Traceback (most recent call last):
  File "C:\Software\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Software\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Software\python\lib\site-packages\FreeTAKServer\controllers\services\FTS.py", line 14, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "C:\Software\python\lib\site-packages\FreeTAKServer\controllers\services\TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "C:\Software\python\lib\site-packages\FreeTAKServer\controllers\services\DataPackageServer.py", line 18, in <module>
    from FreeTAKServer.controllers.DatabaseControllers.DatabaseController import DatabaseController
  File "C:\Software\python\lib\site-packages\FreeTAKServer\controllers\DatabaseControllers\DatabaseController.py", line 11, in <module>
    from FreeTAKServer.controllers.configuration.DatabaseConfiguration import DatabaseConfiguration
  File "C:\Software\python\lib\site-packages\FreeTAKServer\controllers\configuration\DatabaseConfiguration.py", line 3, in <module>
    class DatabaseConfiguration:
  File "C:\Software\python\lib\site-packages\FreeTAKServer\controllers\configuration\DatabaseConfiguration.py", line 5, in DatabaseConfiguration
    if MainConfig.DataBaseType == "SQLite":
AttributeError: type object 'MainConfig' has no attribute 'DataBaseType'

Then when attempting to start the GUI:

C:\Users\richg>cd C:\Software\python\Lib\site-packages\FreeTAKServer-UI

C:\Software\python\Lib\site-packages\FreeTAKServer-UI>set FLASK_APP=run.py

C:\Software\python\Lib\site-packages\FreeTAKServer-UI>flask run
 * Serving Flask app "run.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing "FreeTAKServer-UI.run", an ImportError was raised:

Traceback (most recent call last):
  File "C:\Software\python\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Software\python\Lib\site-packages\FreeTAKServer-UI\run.py", line 38, in <module>
    from config import config_dict
ModuleNotFoundError: No module named 'config'

I'm sure it's something silly I've done.  Thanks in advance.

**Comment by Cale-Torino** [comment]
If you're going to use windows try the Docker version or the [FTSManager](https://github.com/Cale-Torino/FreeTAKServer_Manager "FTSManager"). 
However the Linux version is still the best approach if your PC can handle it use a virtual Linux distro, just my 2cents.

**Comment by brothercorvo** [comment]
![image](https://user-images.githubusercontent.com/60719165/173190838-d5967b01-ea32-4c72-bba3-2c84c09ca821.png)
@rcgordy please follow the instructions here

**Comment by rcgordy** [comment]
This worked, thank you.
