### ISSUE TITLE
Issue when using the Zero Touch Installation

### ISSUE THREAD

**Issue by MasterPuffin** [FreeTAKTeam/FreeTakServer#352]
When using the Zero Touch Installation it aborts with the following error message

`No package matching 'python3.8' is available`
when installing Python beforehand with the following commands, the error doesn't occur

```
sudo apt install python3.8
sudo add-apt-repository ppa:deadsnakes/ppa
```

OS is Ubuntu 20.04

**Comment by HeroesLament** [comment]
1. Can you please provide the link you're using to execute the Zerotouch installer?
2. Can you please execute the Zerotouch installer with the verbose flag?
bash -c "$(wget -qO - 'https://raw.githubusercontent.com/FreeTAKTeam/FreeTAKHub-Installation/main/scripts/easy_install.sh')" '' --verbose

Thank you.

**Comment by MasterPuffin** [comment]
```
root@FreeTAKServer:~# wget -qO - https://raw.githubusercontent.com/FreeTAKTeam/FreeTAKHub-Installation/main/scripts/easy_install.sh | bash
Checking if this script is running as root...Success!
Downloading dependencies...
Adding the Ansible Personal Package Archive (PPA)...
Repository: 'deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/ jammy main'
Description:
Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications— automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.

http://ansible.com/

If you face any issues while installing Ansible PPA, file an issue here:
https://github.com/ansible-community/ppa/issues
More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Adding key to /etc/apt/trusted.gpg.d/ansible-ubuntu-ansible.gpg with fingerprint 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
0% [Working]^CTraceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/apt-add-repository", line 359, in main
    self.apt_update()
  File "/usr/bin/apt-add-repository", line 124, in apt_update
    subprocess.run(['apt-get', 'update'])
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1141, in communicate
    self.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1938, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1896, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
root@FreeTAKServer:~# ^C
root@FreeTAKServer:~# docker volume create fts_data
Command 'docker' not found, but can be installed with:
apt install docker.io      # version 20.10.12-0ubuntu4, or
apt install podman-docker  # version 3.4.4+ds1-1ubuntu1
root@FreeTAKServer:~# sudo apt install docker
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1337 (apt-get)      
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1337 (apt-get)      
Reading package lists... Done                                                                               
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  wmdocker
The following NEW packages will be installed:
  docker wmdocker
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.3 kB of archives.
After this operation, 58.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.digitalocean.com/ubuntu jammy/universe amd64 wmdocker amd64 1.5-2 [13.0 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu jammy/universe amd64 docker all 1.5-2 [1316 B]
Fetched 14.3 kB in 6s (2295 B/s)
Selecting previously unselected package wmdocker.
(Reading database ... 64237 files and directories currently installed.)
Preparing to unpack .../wmdocker_1.5-2_amd64.deb ...
Unpacking wmdocker (1.5-2) ...
Selecting previously unselected package docker.
Preparing to unpack .../archives/docker_1.5-2_all.deb ...
Unpacking docker (1.5-2) ...
Setting up wmdocker (1.5-2) ...
Setting up docker (1.5-2) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...                                                                                                                      
Scanning linux images...                                                                                                                   

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@FreeTAKServer:~# docker volume create fts_data
Command 'docker' not found, but can be installed with:
apt install docker.io      # version 20.10.12-0ubuntu4, or
apt install podman-docker  # version 3.4.4+ds1-1ubuntu1
root@FreeTAKServer:~# docker volume create fts_data
Command 'docker' not found, but can be installed with:
apt install docker.io      # version 20.10.12-0ubuntu4, or
apt install podman-docker  # version 3.4.4+ds1-1ubuntu1
root@FreeTAKServer:~# sudo apt install docker.io
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  bridge-utils containerd dns-root-data dnsmasq-base pigz runc ubuntu-fan
Suggested packages:
  ifupdown aufs-tools cgroupfs-mount | cgroup-lite debootstrap docker-doc rinse zfs-fuse | zfsutils
The following NEW packages will be installed:
  bridge-utils containerd dns-root-data dnsmasq-base docker.io pigz runc ubuntu-fan
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 65.6 MB of archives.
After this operation, 283 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.digitalocean.com/ubuntu jammy/universe amd64 pigz amd64 2.6-1 [63.6 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu jammy/main amd64 bridge-utils amd64 1.7-1ubuntu3 [34.4 kB]
Get:3 http://mirrors.digitalocean.com/ubuntu jammy/main amd64 runc amd64 1.1.0-0ubuntu1 [4087 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu jammy/main amd64 containerd amd64 1.5.9-0ubuntu3 [27.0 MB]
Get:5 http://mirrors.digitalocean.com/ubuntu jammy/main amd64 dns-root-data all 2021011101 [5256 B]
Get:6 http://mirrors.digitalocean.com/ubuntu jammy-updates/main amd64 dnsmasq-base amd64 2.86-1.1ubuntu0.1 [354 kB]
Get:7 http://mirrors.digitalocean.com/ubuntu jammy/universe amd64 docker.io amd64 20.10.12-0ubuntu4 [34.0 MB]
Get:8 http://mirrors.digitalocean.com/ubuntu jammy/universe amd64 ubuntu-fan all 0.12.16 [35.2 kB]
Fetched 65.6 MB in 1s (50.1 MB/s)
Preconfiguring packages ...
Selecting previously unselected package pigz.
(Reading database ... 64247 files and directories currently installed.)
Preparing to unpack .../0-pigz_2.6-1_amd64.deb ...
Unpacking pigz (2.6-1) ...
Selecting previously unselected package bridge-utils.
Preparing to unpack .../1-bridge-utils_1.7-1ubuntu3_amd64.deb ...
Unpacking bridge-utils (1.7-1ubuntu3) ...
Selecting previously unselected package runc.
Preparing to unpack .../2-runc_1.1.0-0ubuntu1_amd64.deb ...
Unpacking runc (1.1.0-0ubuntu1) ...
Selecting previously unselected package containerd.
Preparing to unpack .../3-containerd_1.5.9-0ubuntu3_amd64.deb ...
Unpacking containerd (1.5.9-0ubuntu3) ...
Selecting previously unselected package dns-root-data.
Preparing to unpack .../4-dns-root-data_2021011101_all.deb ...
Unpacking dns-root-data (2021011101) ...
Selecting previously unselected package dnsmasq-base.
Preparing to unpack .../5-dnsmasq-base_2.86-1.1ubuntu0.1_amd64.deb ...
Unpacking dnsmasq-base (2.86-1.1ubuntu0.1) ...
Selecting previously unselected package docker.io.
Preparing to unpack .../6-docker.io_20.10.12-0ubuntu4_amd64.deb ...
Unpacking docker.io (20.10.12-0ubuntu4) ...
Selecting previously unselected package ubuntu-fan.
Preparing to unpack .../7-ubuntu-fan_0.12.16_all.deb ...
Unpacking ubuntu-fan (0.12.16) ...
Setting up dnsmasq-base (2.86-1.1ubuntu0.1) ...
Setting up runc (1.1.0-0ubuntu1) ...
Setting up dns-root-data (2021011101) ...
Setting up bridge-utils (1.7-1ubuntu3) ...
Setting up pigz (2.6-1) ...
Setting up containerd (1.5.9-0ubuntu3) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
Setting up ubuntu-fan (0.12.16) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-fan.service → /lib/systemd/system/ubuntu-fan.service.
Setting up docker.io (20.10.12-0ubuntu4) ...
Adding group `docker' (GID 120) ...
Done.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Processing triggers for dbus (1.12.20-2ubuntu4) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...                                                                                                                      
Scanning linux images...                                                                                                                   

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
root@FreeTAKServer:~# docker run -d -p 8080:8080/tcp -p 8087:8087/tcp -e FTS_CONNECTION_MESSAGE="Server Connection Message" -e FTS_COT_TO_DB="True" -v fts_data:/data --name fts --restart unless-stopped freetakteam/freetakserver:1.1.2
Unable to find image 'freetakteam/freetakserver:1.1.2' locally
1.1.2: Pulling from freetakteam/freetakserver
bb79b6b2107f: Pull complete 
594310e67120: Pull complete 
780e9f0698ad: Pull complete 
a1ba01c36ef6: Pull complete 
aa142b781142: Pull complete 
d3af1aac1c42: Pull complete 
1c94b7953525: Pull complete 
Digest: sha256:f4356630f041a1601780717ef183876d08f28864c933804904ebef60d5ea39f7
Status: Downloaded newer image for freetakteam/freetakserver:1.1.2
7d73c6951f402b128533921a017ab3d477c477e8a68c50f269132ebd3e9e782b
root@FreeTAKServer:~# docker ls
docker: 'ls' is not a docker command.
See 'docker --help'
root@FreeTAKServer:~# docker list
docker: 'list' is not a docker command.
See 'docker --help'
root@FreeTAKServer:~# docker container ls       
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS         PORTS                                                                                  NAMES
7d73c6951f40   freetakteam/freetakserver:1.1.2   "/bin/bash /start-ft…"   9 minutes ago   Up 9 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8087->8087/tcp, :::8087->8087/tcp   fts
root@FreeTAKServer:~# ^C
root@FreeTAKServer:~# docker container stop 7d73c6951f40
7d73c6951f40
root@FreeTAKServer:~# bash -c "$(wget -qO - 'https://raw.githubusercontent.com/FreeTAKTeam/FreeTAKHub-Installation/main/scripts/easy_install.sh')" '' --verbose
+ NO_COLOR=1
+ GIT_TRACE=true
+ GIT_CURL_VERBOSE=true
+ GIT_SSH_COMMAND='ssh -vvv'
+ unset APT_VERBOSITY
+ ANSIBLE_VERBOSITY=-vv
+ shift
+ true
+ case "${1-}" in
+ break
+ setup_colors
+ [[ -t 2 ]]
+ [[ -z 1 ]]
+ NOFORMAT=
+ RED=
+ GREEN=
+ BLUE=
+ YELLOW=
+ do_checks
+ check_root
+ echo -e -n 'Checking if this script is running as root...'
Checking if this script is running as root...+ [[ 0 -ne 0 ]]
+ echo -e 'Success!'
Success!
+ [[ -n '' ]]
+ WEBMAP_FORCE_INSTALL='-e webmap_force_install=true'
+ [[ -n '' ]]
+ download_dependencies
+ echo -e 'Downloading dependencies...'
Downloading dependencies...
+ echo -e 'Adding the Ansible Personal Package Archive (PPA)...'
Adding the Ansible Personal Package Archive (PPA)...
+ sudo apt-add-repository -y ppa:ansible/ansible
Repository: 'deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/ jammy main'
Description:
Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications— automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.

http://ansible.com/

If you face any issues while installing Ansible PPA, file an issue here:
https://github.com/ansible-community/ppa/issues
More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Adding deb entry to /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Adding key to /etc/apt/trusted.gpg.d/ansible-ubuntu-ansible.gpg with fingerprint 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease                                                           
Hit:3 http://mirrors.digitalocean.com/ubuntu jammy InRelease                                                                            
Get:4 https://ppa.launchpadcontent.net/ansible/ansible/ubuntu jammy InRelease [18.0 kB]                           
Get:5 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease [114 kB]
Get:6 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [228 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [56.1 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [94.1 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [33.2 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [2172 B]
Get:12 http://mirrors.digitalocean.com/ubuntu jammy-updates/main amd64 Packages [381 kB]
Get:13 http://mirrors.digitalocean.com/ubuntu jammy-updates/main Translation-en [96.3 kB]
Get:14 http://mirrors.digitalocean.com/ubuntu jammy-updates/universe amd64 Packages [171 kB]
Get:15 http://mirrors.digitalocean.com/ubuntu jammy-updates/universe Translation-en [60.7 kB]
Get:16 http://mirrors.digitalocean.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [4224 B]
Get:17 https://ppa.launchpadcontent.net/ansible/ansible/ubuntu jammy/main amd64 Packages [1132 B]
Get:18 https://ppa.launchpadcontent.net/ansible/ansible/ubuntu jammy/main Translation-en [756 B]
Fetched 1471 kB in 1s (1149 kB/s)                            
Reading package lists... Done
+ echo -e 'Downloading package information from configured sources...'
Downloading package information from configured sources...
+ sudo apt-get -y -qq update
+ echo -e 'Installing Ansible...'
Installing Ansible...
+ sudo apt-get -y -qq install ansible
Selecting previously unselected package python3-packaging.
(Reading database ... 64601 files and directories currently installed.)
Preparing to unpack .../00-python3-packaging_21.3-1_all.deb ...
Unpacking python3-packaging (21.3-1) ...
Selecting previously unselected package python3-resolvelib.
Preparing to unpack .../01-python3-resolvelib_0.8.1-1_all.deb ...
Unpacking python3-resolvelib (0.8.1-1) ...
Selecting previously unselected package ansible-core.
Preparing to unpack .../02-ansible-core_2.13.2-1ppa~jammy_all.deb ...
Unpacking ansible-core (2.13.2-1ppa~jammy) ...
Selecting previously unselected package ansible.
Preparing to unpack .../03-ansible_6.1.0-1ppa~jammy_all.deb ...
Unpacking ansible (6.1.0-1ppa~jammy) ...
Selecting previously unselected package python3-jmespath.
Preparing to unpack .../04-python3-jmespath_0.10.0-1_all.deb ...
Unpacking python3-jmespath (0.10.0-1) ...
Selecting previously unselected package python3-kerberos.
Preparing to unpack .../05-python3-kerberos_1.1.14-3.1build5_amd64.deb ...
Unpacking python3-kerberos (1.1.14-3.1build5) ...
Selecting previously unselected package python3-nacl.
Preparing to unpack .../06-python3-nacl_1.5.0-2_amd64.deb ...
Unpacking python3-nacl (1.5.0-2) ...
Selecting previously unselected package python3-ntlm-auth.
Preparing to unpack .../07-python3-ntlm-auth_1.4.0-1_all.deb ...
Unpacking python3-ntlm-auth (1.4.0-1) ...
Selecting previously unselected package python3-paramiko.
Preparing to unpack .../08-python3-paramiko_2.9.3-0ubuntu1_all.deb ...
Unpacking python3-paramiko (2.9.3-0ubuntu1) ...
Selecting previously unselected package python3-requests-kerberos.
Preparing to unpack .../09-python3-requests-kerberos_0.12.0-2_all.deb ...
Unpacking python3-requests-kerberos (0.12.0-2) ...
Selecting previously unselected package python3-requests-ntlm.
Preparing to unpack .../10-python3-requests-ntlm_1.1.0-1.1_all.deb ...
Unpacking python3-requests-ntlm (1.1.0-1.1) ...
Selecting previously unselected package python3-xmltodict.
Preparing to unpack .../11-python3-xmltodict_0.12.0-2_all.deb ...
Unpacking python3-xmltodict (0.12.0-2) ...
Selecting previously unselected package python3-winrm.
Preparing to unpack .../12-python3-winrm_0.3.0-2_all.deb ...
Unpacking python3-winrm (0.3.0-2) ...
Selecting previously unselected package sshpass.
Preparing to unpack .../13-sshpass_1.09-1_amd64.deb ...
Unpacking sshpass (1.09-1) ...
Setting up python3-ntlm-auth (1.4.0-1) ...
Setting up python3-resolvelib (0.8.1-1) ...
Setting up python3-kerberos (1.1.14-3.1build5) ...
Setting up sshpass (1.09-1) ...
Setting up python3-xmltodict (0.12.0-2) ...
Setting up python3-packaging (21.3-1) ...
Setting up python3-jmespath (0.10.0-1) ...
Setting up python3-requests-kerberos (0.12.0-2) ...
Setting up python3-nacl (1.5.0-2) ...
Setting up python3-requests-ntlm (1.1.0-1.1) ...
Setting up ansible-core (2.13.2-1ppa~jammy) ...
Setting up python3-winrm (0.3.0-2) ...
Setting up ansible (6.1.0-1ppa~jammy) ...
Setting up python3-paramiko (2.9.3-0ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...                                                                                                                      
Scanning linux images...                                                                                                                   

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
+ echo -e 'Installing Git...'
Installing Git...
+ sudo apt-get -y -qq install git
+ handle_git_repository
+ echo -e -n 'Checking for FreeTAKHub-Installation in home directory...'
Checking for FreeTAKHub-Installation in home directory...+ cd /root
+ [[ ! -d /root/FreeTAKHub-Installation ]]
+ echo -e 'NOT FOUND'
NOT FOUND
+ echo -e 'Cloning the FreeTAKHub-Installation repository...'
Cloning the FreeTAKHub-Installation repository...
+ git clone https://github.com/FreeTAKTeam/FreeTAKHub-Installation.git
Cloning into 'FreeTAKHub-Installation'...
remote: Enumerating objects: 3373, done.
remote: Counting objects: 100% (695/695), done.
remote: Compressing objects: 100% (248/248), done.
remote: Total 3373 (delta 436), reused 668 (delta 422), pack-reused 2678
Receiving objects: 100% (3373/3373), 96.70 MiB | 23.64 MiB/s, done.
Resolving deltas: 100% (1898/1898), done.
+ cd /root/FreeTAKHub-Installation
+ add_passwordless_ansible_execution
+ echo -e 'Adding passwordless Ansible execution for the current user...'
Adding passwordless Ansible execution for the current user...
+ LINE='root ALL=(ALL) NOPASSWD:/usr/bin/ansible-playbook'
+ FILE=/etc/sudoers.d/dont-prompt-root-for-sudo-password
+ grep -qF -- 'root ALL=(ALL) NOPASSWD:/usr/bin/ansible-playbook' /etc/sudoers.d/dont-prompt-root-for-sudo-password
grep: /etc/sudoers.d/dont-prompt-root-for-sudo-password: No such file or directory
+ echo 'root ALL=(ALL) NOPASSWD:/usr/bin/ansible-playbook'
+ generate_key_pair
+ echo -e 'Creating a public and private keys if non-existent...'
Creating a public and private keys if non-existent...
+ [[ ! -e /root/.ssh/id_rsa.pub ]]
+ ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
Generating public/private rsa key pair.
Your identification has been saved in /root/.ssh/id_rsa
Your public key has been saved in /root/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:N/E/sM3kziHHcT84QIVQcztm4uC8/Qb1jAKjVWUQVNw root@FreeTAKServer
The key's randomart image is:
+---[RSA 3072]----+
|         .+*B*.  |
|           o=..E |
|         .oo =   |
|        o++o+..  |
|        So=o+ * .|
|       . .o+.@.=.|
|         . .=oX..|
|            .*.o.|
|            ..o  |
+----[SHA256]-----+
+ run_playbook
+ echo -e 'Running Ansible Playbook...'
Running Ansible Playbook...
+ [[ -n '' ]]
+ ansible-playbook -u root -i localhost, --connection=local -e webmap_force_install=true install_all.yml -vv
ansible-playbook [core 2.13.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
statically imported: /root/FreeTAKHub-Installation/roles/common/tasks/cleanup.yml
statically imported: /root/FreeTAKHub-Installation/roles/nodered/tasks/reload-flows.yml
statically imported: /root/FreeTAKHub-Installation/roles/common/tasks/cleanup.yml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: install_all.yml *****************************************************************************************************************1 plays in install_all.yml

PLAY [Install FreeTAKServer and all components] *******************************************************************************************
TASK [Gathering Facts] ********************************************************************************************************************task path: /root/FreeTAKHub-Installation/install_all.yml:2
ok: [localhost]

TASK [cleanup /tmp/*] *********************************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/common/tasks/cleanup.yml:2
changed: [localhost] => {"changed": true, "cmd": "sudo rm -rf /tmp/*", "delta": "0:00:00.031586", "end": "2022-07-23 18:27:21.243269", "msg": "", "rc": 0, "start": "2022-07-23 18:27:21.211683", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
META: ran handlers

TASK [common : Include Ubuntu-specific variables] *****************************************************************************************task path: /root/FreeTAKHub-Installation/roles/common/tasks/main.yml:2
ok: [localhost] => {"ansible_facts": {"unit_files_location": "/etc/systemd/system"}, "ansible_included_var_files": ["/root/FreeTAKHub-Installation/roles/common/vars/Ubuntu.yml"], "changed": false}

TASK [common : Setup] *********************************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/common/tasks/main.yml:5
included: /root/FreeTAKHub-Installation/roles/common/tasks/setup-Ubuntu.yml for localhost

TASK [common : Update apt] ****************************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/common/tasks/setup-Ubuntu.yml:2
ok: [localhost] => {"attempts": 1, "changed": false, "cmd": "sudo apt update", "delta": "0:00:03.465031", "end": "2022-07-23 18:27:25.205313", "msg": "", "rc": 0, "start": "2022-07-23 18:27:21.740282", "stderr": "\nWARNING: apt does not have a stable CLI interface. Use with caution in scripts.", "stderr_lines": ["", "WARNING: apt does not have a stable CLI interface. Use with caution in scripts."], "stdout": "Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease\nHit:2 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease\nHit:3 http://mirrors.digitalocean.com/ubuntu jammy InRelease\nHit:4 https://ppa.launchpadcontent.net/ansible/ansible/ubuntu jammy InRelease\nHit:5 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease\nHit:6 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease\nReading package lists...\nBuilding dependency tree...\nReading state information...\n2 packages can be upgraded. Run 'apt list --upgradable' to see them.", "stdout_lines": ["Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease", "Hit:2 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease", "Hit:3 http://mirrors.digitalocean.com/ubuntu jammy InRelease", "Hit:4 https://ppa.launchpadcontent.net/ansible/ansible/ubuntu jammy InRelease", "Hit:5 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease", "Hit:6 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease", "Reading package lists...", "Building dependency tree...", "Reading state information...", "2 packages can be upgraded. Run 'apt list --upgradable' to see them."]}

TASK [common : Detect systemctl file] *****************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/common/tasks/setup-Ubuntu.yml:10
ok: [localhost] => {"changed": false, "stat": {"exists": false}}

TASK [common : Create systemctl backup] ***************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/common/tasks/setup-Ubuntu.yml:15
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [common : Use systemctl workaround] **************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/common/tasks/setup-Ubuntu.yml:22
changed: [localhost] => {"changed": true, "checksum_dest": null, "checksum_src": "feb6b085e2da03491676d948846de3b16aad512e", "dest": "/usr/local/bin/systemctl", "elapsed": 0, "gid": 0, "group": "root", "md5sum": "e7642998d542ee670b8f29308420d9da", "mode": "0755", "msg": "OK (291429 bytes)", "owner": "root", "size": 291429, "src": "/root/.ansible/tmp/ansible-tmp-1658600846.0152133-4977-229842589090705/tmpbdb3zf_c", "state": "file", "status_code": 200, "uid": 0, "url": "https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py"}
META: role_complete for localhost

TASK [python3 : Setup] ********************************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/python3/tasks/main.yml:2
included: /root/FreeTAKHub-Installation/roles/python3/tasks/setup-Ubuntu.yml for localhost

TASK [python3 : Include Ubuntu-specific variables] ****************************************************************************************task path: /root/FreeTAKHub-Installation/roles/python3/tasks/setup-Ubuntu.yml:2
ok: [localhost] => {"ansible_facts": {"pip3_packages": ["pyyaml"], "python3_apt_packages": ["python3-pip", "python3-distutils", "python{{ python3_version }}"]}, "ansible_included_var_files": ["/root/FreeTAKHub-Installation/roles/python3/vars/Ubuntu.yml"], "changed": false}

TASK [python3 : Install apt packages] *****************************************************************************************************task path: /root/FreeTAKHub-Installation/roles/python3/tasks/setup-Ubuntu.yml:5
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'python3.8' is available"}

PLAY RECAP ********************************************************************************************************************************localhost                  : ok=9    changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

+ cleanup
+ trap - SIGINT SIGTERM ERR EXIT
root@FreeTAKServer:~#
```

**Comment by HeroesLament** [comment]
You can see right away what the problem is in the first stacktrace. Your OS has python3.10 installed, and you have Ubuntu Jammy chosen, instead of 20.04 LTS Xenial. Please rebuild with a Ubuntu 20.04 LTS image or downgrade your python installation from 3.10 to 3.8 manually prior to executing the Zerotouch installer.

**Comment by MasterPuffin** [comment]
In this case, the issue is with DigitalOcean, as this should be a 20.04 LTS image. I'll try using the correct image, thank you for your help!
