### ISSUE TITLE
FreeTAKServer on RPi 3 Error 98 Exceptions

### ISSUE THREAD

**Issue by DaveyDave123** [FreeTAKTeam/FreeTakServer#401]
Hi. I'm attempting to run FreeTAKServer on a RPi and experiencing issues with 'Address already in use' and exceptions. I'm using python 3.9 and what I believe to be an appropriate configured MainConfig.py. Installation as per:
https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Docker/Raspberry%20Pi/
with follow up execution guidance from here:
https://www.youtube.com/watch?v=eMh9G96-npw

Any pointers would be greatly appreciated - thank you.

Dave

hh-takserver@raspberrypi:/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/configuration $ sudo python3 -m FreeTAKServer.controllers.services.FTS
would you like to use a yaml config file, 
 if yes you will be prompted for further configuration options [yes]: yes
where would you like to save the yaml config [/opt/FTSConfig.yaml]: y
enter ip [192.168.1.10]: 
192.168.1.10
192.168.1.10
enter the preferred database type (MySQL is highly experimental if you're not sure leave default) [SQLite]: 
enter the preferred database path [/opt/FTSDataBase.db]: 
/opt/FTSDataBase.db
enter the preferred main_path [/usr/local/lib/python3.9/dist-packages/FreeTAKServer]: 
/usr/local/lib/python3.9/dist-packages/FreeTAKServer
enter the preferred log file path [/usr/local/lib/python3.9/dist-packages/FreeTAKServer/Logs]: 
/usr/local/lib/python3.9/dist-packages/FreeTAKServer/Logs
CA found locally, not generating a new one
Certificate file exists, aborting.
Certificate file exists, aborting.
something
start 213
starting now
Exception ignored in: <function _after_fork at 0x72497028>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
Exception ignored in: <function _after_fork at 0x72497028>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
running api
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
0.0.0.0
8080
there has been an exception in Data Package service startup [Errno 98] Address already in use
start 213
starting SSL now
Exception ignored in: <function _after_fork at 0x72497028>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
0.0.0.0
8443
(1917) wsgi starting up on https://0.0.0.0:8443
event event about to be created
CoTService started
Exception ignored in: <function _after_fork at 0x72497028>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
SSL CoTService started
Exception ignored in: <function _after_fork at 0x72497028>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
Exception ignored in: <function _after_fork at 0x72497028>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1490, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
{}
    self._lock._at_fork_reinit()
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
number of CoT messages received by services: 0
there has been an exception in the start function of TCPCoTService [Errno 98] Address already in use
started federation federate service
ssl cot service starting
server started

 running ssl 

mainRunFunction is running
client dict: {}
{}
number of CoT messages received by services: 0
{}
number of CoT messages received by services: 0
time since last reset 0:00:30.014496
{}
number of CoT messages received by services: 0
mainRunFunction is running
client dict: {}

**Comment by hickey** [comment]
`docker-pr` is actually `docker-proxy`--it is just getting truncated in the output. This is the part of docker that does some of the port redirection. So somewhere you have a Docker container running that is getting port 8443 redirected to a container port. Looking at the output of `docker ps` should give you a good idea which container it is. 

As to the threading error that you are getting, I can not give you as much of a definitive answer. I just checked the FTS and UI code bases and there are no references I can find for `Semaphore` or the method `after_fork`. The other curious thing is that the exception that is occurring is in the Python standard library not any of the FTS code. Do you have any Python modules that modify how forking or threading operates?

**Comment by naman108** [comment]
My first thought is that given your version (3.9) it's possible that one the libraries FTS is dependent on is incompatible. We don't do much with semaphores as pointed out above, so my first troubleshooting recommendation would be to try do downgrade to the currently supported version 3.8 if at all possible otherwise we can escalate by selectively upgrading potentially culpable libraries.

**Comment by hickey** [comment]
@DaveyDave123 I was looking at the server output again and realized that I mis-read some of the output. I thought that I was reading that FTS was failing to open port 8443. What the output is actually saying is that 8443 was opened correctly, but it is the TCP COT port that is failing. By default that port is 8087. Sorry for sending you down the wrong path.
