### ISSUE TITLE
After 5 mounths running the server, SSL-COT doesn`t work anymore

### ISSUE THREAD

**Issue by Mori0410** [FreeTAKTeam/FreeTakServer#447]
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:2635)
Removing descriptor: 96
(8753) accepted ('128.14.134.134', 52054)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 825, in process_request
    proto.__init__(conn_state, self)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 252, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 267, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 186, in read
    return self._call_trampolining(
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 161, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:2635)
Removing descriptor: 96
(8753) accepted ('138.99.216.228', 61000)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 825, in process_request
    proto.__init__(conn_state, self)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 252, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 267, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 186, in read
    return self._call_trampolining(
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 161, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:2635)
Removing descriptor: 96
(8753) accepted ('104.206.128.6', 49799)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 825, in process_request
    proto.__init__(conn_state, self)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 252, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 267, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 186, in read
    return self._call_trampolining(
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 161, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: PEER_DID_NOT_RETURN_A_CERTIFICATE] peer did not return a certificate (_ssl.c:2635)
Removing descriptor: 96
(8753) accepted ('192.241.216.31', 49396)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 825, in process_request
    proto.__init__(conn_state, self)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 252, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 267, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 186, in read
    return self._call_trampolining(
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 161, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:2635)
Removing descriptor: 96
(8753) accepted ('198.199.118.120', 48230)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 825, in process_request
    proto.__init__(conn_state, self)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 252, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 267, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 186, in read
    return self._call_trampolining(
  File "/usr/local/lib/python3.8/dist-packages/eventlet/green/ssl.py", line 161, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

**Comment by brothercorvo** [comment]
duplicates of #368 
this is depending on the CRL as documented [here](https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Troubleshooting/SocketIssue/). We have now created a script to fix it

**Comment by brothercorvo** [comment]
this is now fixed in 2.1
