### ISSUE TITLE
Issue installing FreeTAKServer with pip (Ubuntu Server 22.10)

### ISSUE THREAD

**Issue by daskalovst** [FreeTAKTeam/FreeTakServer#528]
sudo python3 -m pip install FreeTAKServer[ui]
Collecting FreeTAKServer[ui]
  Using cached FreeTAKServer-1.9.9.6-py3-none-any.whl (333 kB)
Collecting defusedxml==0.7.1
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting geopy==2.2.0
  Using cached geopy-2.2.0-py3-none-any.whl (118 kB)
Collecting colorama==0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: MarkupSafe==2.0.1 in /usr/lib/python3/dist-packages (from FreeTAKServer[ui]) (2.0.1)
Collecting PyYAML==6.0
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-socketio==4.6.0
  Using cached python_socketio-4.6.0-py2.py3-none-any.whl (51 kB)
Collecting qrcode==7.3.1
  Using cached qrcode-7.3.1.tar.gz (43 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting WTForms==2.3.3
  Downloading WTForms-2.3.3-py2.py3-none-any.whl (169 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.1/169.1 kB 2.3 MB/s eta 0:00:00
Collecting Flask-SQLAlchemy==2.4.4
  Using cached Flask_SQLAlchemy-2.4.4-py2.py3-none-any.whl (17 kB)
Collecting click==8.0.4
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting lxml==4.6.5
  Using cached lxml-4.6.5.tar.gz (3.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Building lxml version 4.6.5.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
***
ubuntu@ubuntu:~$ sudo pip3 install lxml
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (4.9.1)

**Comment by hickey** [comment]
Do you have `libxml2-dev` and `libxslt-dev` installed?

**Comment by daskalovst** [comment]
same thing but with different error
why is so difficult to be listed all dependencies and the proper versions

sudo python3 -m pip install FreeTAKServer[ui]
Collecting FreeTAKServer[ui]
  Using cached FreeTAKServer-1.9.9.6-py3-none-any.whl (333 kB)
Collecting psutil==5.9.0
  Downloading psutil-5.9.0.tar.gz (478 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 478.3/478.3 KB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: colorama==0.4.4 in /usr/lib/python3/dist-packages (from FreeTAKServer[ui]) (0.4.4)
Collecting python-engineio==3.13.2
  Downloading python_engineio-3.13.2-py2.py3-none-any.whl (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 KB 887.6 kB/s eta 0:00:00
Collecting click==8.0.4
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting ruamel.yaml==0.17.21
  Downloading ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 KB 1.5 MB/s eta 0:00:00
Collecting pillow==9.1.1
  Downloading Pillow-9.1.1.tar.gz (49.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.8/49.8 MB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: greenlet==1.1.2 in /usr/lib/python3/dist-packages (from FreeTAKServer[ui]) (1.1.2)
Collecting Flask-Cors==3.0.9
  Downloading Flask_Cors-3.0.9-py2.py3-none-any.whl (14 kB)
Collecting defusedxml==0.7.1
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting pathlib2==2.3.7.post1
  Using cached pathlib2-2.3.7.post1-py2.py3-none-any.whl (18 kB)
Collecting geopy==2.2.0
  Downloading geopy-2.2.0-py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 KB 562.5 kB/s eta 0:00:00
Collecting Flask-Login==0.5.0
  Downloading Flask_Login-0.5.0-py2.py3-none-any.whl (16 kB)
Collecting pykml==0.2.0
  Downloading pykml-0.2.0-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.1/41.1 KB 714.3 kB/s eta 0:00:00
Collecting dnspython==1.16.0
  Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 KB 1.4 MB/s eta 0:00:00
Collecting eventlet==0.29.0
  Using cached eventlet-0.29.0-py2.py3-none-any.whl (223 kB)
Collecting PyYAML==6.0
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 KB 423.0 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: MarkupSafe==2.0.1 in /usr/lib/python3/dist-packages (from FreeTAKServer[ui]) (2.0.1)
Collecting Jinja2==2.11.2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting python-socketio==4.6.0
  Downloading python_socketio-4.6.0-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 KB 626.1 kB/s eta 0:00:00
Collecting cryptography==36.0.2
  Downloading cryptography-36.0.2.tar.gz (572 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.1/572.1 KB 1.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      
              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:
      
              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
              =============================DEBUG ASSISTANCE==========================
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 14, in <module>
          from setuptools_rust import RustExtension
        File "/tmp/pip-build-env-lo8dt56a/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-lo8dt56a/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SCWhite** [comment]
HI @daskalovst 
seems there is a problem with your environment
try
`pip install –upgrade wheel`
`pip install –upgrade setuptools` 

and maybe, go back to a previous version and try again?

**Comment by brothercorvo** [comment]
1.9.9.6 does not support ubuntu 22
2.0 Alpha does

**Comment by brothercorvo** [comment]
please use FTS 2.1, closing this
