### ISSUE TITLE
Issue installing FreeTAKServer with pip latest rasbian

### ISSUE THREAD

**Issue by daskalovst** [FreeTAKTeam/FreeTakServer#529]
sudo python3 -m FreeTAKServer.controllers.services.FTS 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 14, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.9/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 57, in <module>
    os.mkdir(MainConfig.ExCheckMainPath)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/FreeTAKServer/ExCheck'

**Comment by hickey** [comment]
This is actually (and unfortunately) expected because you have a different version of Python installed. The new code base does not use a static Python library path. As a quick fix you could just create a symbolic link to your real Python library. The other option is to install with the new code base.

**Comment by hickey** [comment]
Since this is a pretty much a known issue, I am going to go ahead and close this issue. If you have more information that you think is related or need more help with how to proceed, please feel free to re-open this issue and add more comments.
