### ISSUE TITLE
Mission tab under UI not reachable

### ISSUE THREAD

**Issue by Thompson78** [FreeTAKTeam/FreeTakServer#649]
after fresh install the "Mission" Tab under the UI is nor rechable anymore...

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/eventlet/wsgi.py", line 569, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/FreeTAKServer-UI/app/home/routes.py", line 68, in missionApi
    excheck_json_data = excheck_json_data['data'][0]['contents'],
KeyError: 'data'

**Comment by brothercorvo** [comment]
You are using python 3.9. 
Upgrade to 3.11

**Comment by Thompson78** [comment]
Thank you for the reply!

I´m on 20.04....

so i made a fresh install of the OS, updatet it, installed python 3.11 and linked it to the 3.11 "sudo ln -s /usr/local/bin/python3.11 /usr/bin/python"

but no luck, same error...FTS is still running from 3.8...i dont know what to do.

**Comment by brothercorvo** [comment]
we test FTS with Ubuntu 22.04 and Python 3.11 to avoid issues with libraries dependencies. if you use a different combination you can expect to have some issue and we can not support all the combinations

**Comment by brothercorvo** [comment]
@Thompson78 please test the new ZeroTouch installation that should solve your issue

**Comment by brothercorvo** [comment]
last tests have not replicated this, closing
