### ISSUE TITLE
Mission 'Data' Error and active issue

### ISSUE THREAD

**Issue by carlitel** [FreeTAKTeam/FreeTakServer#690]
I'm having some troubles with the server.
1: Can't join Mission cuz im getting this error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/eventlet/wsgi.py", line 569, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/FreeTAKServer-UI/app/home/routes.py", line 68, in missionApi
    excheck_json_data = excheck_json_data['data'][0]['contents'],
KeyError: 'data'
<
2: When I check the service status this appears but web ui works good

>
● FreeTAKServer.service
     Loaded: loaded (/etc/systemd/system/FreeTAKServer.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2024-04-12 15:27:24 UTC; 2min 15s ago
    Process: 1398 ExecStart=/usr/bin/sudo python3 /usr/bin/python3.8/dist-packages/FreeTAKServer-UI/run.py (code=exited, status=>
   Main PID: 1398 (code=exited, status=2)

Apr 12 15:27:23 x[1]: FreeTAKServer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 12 15:27:23 x[1]: FreeTAKServer.service: Failed with result 'exit-code'.
Apr 12 15:27:24 x[1]: FreeTAKServer.service: Scheduled restart job, restart counter is at 5.
Apr 12 15:27:24 x[1]: Stopped FreeTAKServer.service.
Apr 12 15:27:24 x[1]: FreeTAKServer.service: Start request repeated too quickly.
Apr 12 15:27:24 x[1]: FreeTAKServer.service: Failed with result 'exit-code'.
Apr 12 15:27:24 x[1]: Failed to start FreeTAKServer.service.
Apr 12 15:29:37 x[1]: /etc/systemd/system/FreeTAKServer.service:1: Unknown section 'UNIT'. Ignoring.
Apr 12 15:29:40 x[1]: /etc/systemd/system/FreeTAKServer.service:1: Unknown section 'UNIT'. Ignoring.
<

**Comment by carlitel** [comment]
I'd like to know if someone can help me with this...

**Comment by brothercorvo** [comment]
You are using a non supported version of Python. The supported version is 3.11
