### ISSUE TITLE
Exception thrown by spawn when starting CoT service

### ISSUE THREAD

**Issue by sgarfinkel** [FreeTAKTeam/FreeTakServer#79]
I am on Mac Catalina, unsure if this is an OS-specific weirdness though.

Here's the full stacktrace:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sgarfinkel/.asdf/installs/python/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/sgarfinkel/.asdf/installs/python/3.8.2/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/sgarfinkel/.asdf/installs/python/3.8.2/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

I found a nearly identical issue here: https://github.com/pytorch/pytorch/issues/30461

Without looking at the underlying source code for starting the CoT service, I suspect the issue is that there are shared file handles between the parent and child processes which are being garbage collected. The docs specifically say that certain file handles won't be inherited when starting a process with `spawn` mode: https://stackoverflow.com/questions/52869833/garbage-collection-of-shared-data-in-multiprocessing-via-fork

On Mac 3.8, `spawn` is the default mode. A solution to this problem is to enforce `fork` mode.

Related StackOverflow post: https://stackoverflow.com/questions/52869833/garbage-collection-of-shared-data-in-multiprocessing-via-fork

**Comment by brothercorvo** [comment]
probably solved in 1.0
