### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str in DataPackageServer.py

### ISSUE THREAD

**Issue by marktimmerman-dev** [FreeTAKTeam/FreeTakServer#84]
On the current master branch, I try to send a photo from one ATAK to another.

INFO : 2020-10-08 09:33:52,729 : DataPackageServer.py:130 : Data Package hash = b149eadf95fee5594bd676dc9534a5dec8fcf533d68519d7b3e305b262c9fce4
ERROR : 2020-10-08 09:33:52,744 : app.py:1891 : Exception on /Marti/sync/missionupload [POST]
Traceback (most recent call last):
  File "/home/##censored##/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/##censored##/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/##censored##/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/##censored##/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/##censored##/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/##censored##/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/disk/src/FreeTakServer/FreeTAKServer/controllers/DataPackageServer.py", line 146, in upload
    return IP+':'+HTTPPORT+"/Marti/api/sync/metadata/"+file_hash+"/tool"
TypeError: can only concatenate str (not "int") to str
192.168.1.114 - - [08/Oct/2020 09:33:52] "POST /Marti/sync/missionupload?hash=b149eadf95fee5594bd676dc9534a5dec8fcf533d68519d7b3e305b262c9fce4&filename=20200527_194658.jpg.zip&creatorUid=ANDROID-358205084015919 HTTP/1.1" 500 -

Solution:
disk/src/FreeTakServer/FreeTAKServer/controllers/DataPackageServer.py", line 146
    return IP+':'+HTTPPORT+"/Marti/api/sync/metadata/"+file_hash+"/tool"

change HTTPPORT to str(HTTPPORT)

**Comment by marktimmerman-dev** [comment]
oh I now see it is correct in the pypi branch.

Is the pypi branch the branch to be used?

**Comment by brothercorvo** [comment]
yes, you should use the pypi to install and maintain FTS. We do not support installations if you use another one
